### ISSUE TITLE
npm package should not be bundled

### ISSUE THREAD

**Issue by squidsoup** [vanilla-framework/vanilla-framework-react#128]
A minimal component importing a single vanilla pattern:

```
import React from 'react';
import { Button } from 'vanilla-framework-react';

const HelloWorld = () => {
  return (
    <div>
      <Button brand value="Hello" />
    </div>
  );
};

HelloWorld.displayName = 'HelloWorld';

export default HelloWorld;
```

produces a payload of 300K+ *after* uglification/minimisation, and results in a Webpack performance warning.

Grepping the resulting artifact, it appears the entirety of vanilla and it's dependencies is included with this component. I would have thought that UglifyJS would catch this for dead-code removal, but it doesn't appear to.

**Comment by squidsoup** [comment]
Having looked at this a bit more closely, it appears that the package published to npm is not a source package, but instead the entry point points to built js. This will effectively kill any dead code elimination that webpack can provide. Could we publish the source instead?

**Comment by Caleb-Ellis** [comment]
@squidsoup Thanks for filing this issue, I'll give it a proper look at next week!

It's 100% *not* at the level to be consumed by production projects yet, as we've yet to really test it outside the safe confines of the Storybook environment (so cozy). Hopefully we'll be shifting some dev focus on this lib soon.

**Comment by squidsoup** [comment]
@Caleb-Ellis cheers Caleb! We have a project coming up soon (~1 month), where it would be great to use `vanilla-framework-react`.

**Comment by bartaz** [comment]
+1 to that. Wanted to give `vanilla-framework-react` a try for snapcraft.io, but (apart from Table issues I reported separately) bundle size was killing the build.

Bundle size is one thing (it made out rollup build to go from seconds to over a minute), it also comes with huge load of dependencies installed by yarn (it added over 4k lines to yarn.lock https://github.com/canonical-websites/snapcraft.io/pull/821/files).
