### ISSUE TITLE
Project cannot be consumed as an NPM lib

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework-react#84]
This project has been published to NPM here...

https://www.npmjs.com/package/vanilla-framework-react

This is so that it can be added as a dep to another React project and individual components can then be added as needs be, but that ain't currently working, see:

https://codesandbox.io/s/qz43rrz259

**Comment by barrymcgee** [comment]
@anthonydillon Why was this closed? I think I should be able to import individual components like so: https://codesandbox.io/s/8nmwzq1z32

Is this no longer the direction of travel?

**Comment by anthonydillon** [comment]
I believe this is the case.
https://www.npmjs.com/package/vanilla-framework-react

You can import each individual component which will add the markup and
functionality. The CSS still needs to be globally imported into the head.

We would like to improve three styling injection but was not a blocker for
this task.
