### ISSUE TITLE
Add run script to create demos

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework-react#9]

**Comment by barrymcgee** [comment]
@nottrobin Is it even possible to hook ./run into sites not set up using the Yeoman generator?

If not, can we disable the ./run demo bot on every PR?

**Comment by nottrobin** [comment]
A site/codebase doesn't use a Yeoman generator. You use a Yeoman generator (globally installed) to update a codebase.

The ./run script can be added manually or through the Yeoman generator, whatever works for you. But for the purposes of demos, obviously it needs some web service to display a demo for. If that's not relevant to this project then you'll definitely want to disable demos somehow. I don't know how to do that - ask @WillMoggridge ?

**Comment by barrymcgee** [comment]
Bump @WillMoggridge ?

**Comment by WillMoggridge** [comment]
I got a quick ./run script working locally but I think #39 needs to be merged first, then I can propose a run script.

**Comment by Caleb-Ellis** [comment]
Issue resolved as of #54
